name: CI without OpenMM

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    # Nightly tests run on master by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 0 * * *"


jobs:
  test:
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { os: ubuntu-latest, python-version: 3.7, torch-version: 'torch>=1.8,<1.9' }
          - { os: ubuntu-latest, python-version: 3.8, torch-version: 'torch>=1.8,<1.9' }
          - { os: ubuntu-latest, python-version: 3.9, torch-version: 'torch>=1.8,<1.9' }
          - { os: ubuntu-latest, python-version: 3.7, torch-version: 'torch>=1.9' }
          - { os: ubuntu-latest, python-version: 3.8, torch-version: 'torch>=1.9' }
          - { os: ubuntu-latest, python-version: 3.9, torch-version: 'torch>=1.9' }
          - { os: windows-latest, python-version: 3.9, torch-version: 'torch>=1.9' }
          - { os: macos-latest, python-version: 3.9, torch-version: 'torch>=1.9' }

    steps:

      # WITHOUT OPENMM
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.cfg.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.cfg.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest "${{ matrix.cfg.torch-version }}" numpy nflows torchdiffeq einops
      - name: Install package
        run: |
          python setup.py install
      - name: Test with pytest
        run: |
          pytest -vs

